repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-toml
      - id: check-executables-have-shebangs
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: "^\\.github/(workflows/.*\\.yml|dependabot\\.yml)$"
        args: [--format, parsable]
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
        files: "^\\.github/(workflows/.*\\.yml|dependabot\\.yml)$"
